spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/parcauto
    username: root
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    path: /api-dpcs
  swagger-ui:
    path: swagger-ui.html
